### PR TITLE
VDOC Launch for realises

### PR DESCRIPTION
**Pull request by RickyCook**

### CODE REVIEW

**Comment by RickyCook** [comment]
... meant to do that in our own fork SORRY!!

**Comment by miohtama** [comment]
No worries @RickyCook 

Just to note that the approach you are doing the whitelisting is less elegant than using signatures in the transactions.

You are now polluting Ethereum state with the whitelist status. This does not need to be the case as you know at the time of the payment if the person is whitelisted or not (you have this information in your database).

**Comment by RickyCook** [comment]
yeah, I totally agree! I love the "stateless login" things similar to JWT. though, we made a decision that we wanted people to be able to pay direct to the contract without adding any transaction data, so the only way that we were able to do that is eschew all the customer ID stuff and tie them to eth addresses. it's less elegant, but much much simpler.

**Comment by miohtama** [comment]
@RickyCook I feel you made a wrong choice.

1. Paying direct to contract is very, very, bad as discussed here 

https://github.com/TokenMarketNet/ico/issues/53

2. You can implement a single click Pay button without gas price, gas limit and data field copy pasting using web3.js and e.g. MetaMask as shown in the screenshots here

https://tokenmarket.net/what-is/how-to-buy-into-a-token-sale-with-metamask-wallet/

**Comment by saravana87** [comment]
@RickyCook how do you transfer eth to smart contract successfully without adding transact data.

Between, I tried to send ETH to crowdsale address using myethwallet.com by connecting meta mask but its still showing error and transaction failed.
https://ropsten.etherscan.io/tx/0x174a997a3b015dec1aed999910604061b45c89666d41f598b59acc41a54f8638

Any advice would be much appreciatable.

**Pull request closed without merging**
